script: npm run deploy
language: node_js
node_js:
- '5'
env:
  global:
  - GH_REF: github.com/cuffs/semantic-ant.git
  - secure: HgLf1v/B5nH8NRSTcMr9YfoU0rFFz5+u3YnKX+gtnEzcIWdJbngi2nshjbdS5gDTEnekM1pXr6gnpIjAQya4caDypbOcIUnIcG18TeetaYdcitVsIYCp7sfBZp0NuFyva/hR9niUCoLzF5gXp0JNiOu1oOUJtS+HnTmWOxqef5hLMAvPpobJbZYoFr7AVePek3hfnb3C/5NNFOw1vGXDUNLcfjJk14aRh5JiUUmZEu0fs3z1vm79mkmzIlcvPvsu/71ep0MByLDiS2eMViJko4xG5Y4tRHq79emCV0+wF0vJKSiBpRjVgvQdzXgEvgr2r4I2tf4jm/l10NI9pymukc2zUzSwU4869+s7CLIV+nqX164/shmDtSfP+xDPz6vaUvEx/rJugsZRhCH67MU6sS8ETukBguimTayfYvR0v73mu5zkkhSsFW6uz9mxZ/SgBddFWFGVQlo2bqgxIwEayWt6earwKCnfq3xvqAZhMnKQBVRjXjLcAZRJzRVW9BlWf3Kndek+Jx0PiDcPW1MILxrUy5urg48MKza++IfdzZo3zN1hv31y8DG5iR3Ehqs9zUY1KkgoxoHcL1Ye8PdwtLWKOsWuqVtkhhKCWdDjJsyHg2x98r1OmlBxS6us84ZKrlXU65UNgjQVum4GyTa6C+oo3OBZyRcAn5ON36IrxUk=
