script: npm run deploy
language: node_js
node_js:
- '5'
env:
  global:
  - GH_REF: github.com/websemantics/semantic-ant.git
  - secure: uP9ryxEOIkEz+Vl7hecWSxemn3u0Hq6T9zGlO6Wurn25F/m59/M+DHRara/2TsiSfIEHKtNFfGMPoQ1aP5UgWFYu6swaebIUzuH9Vzw4dq4+AFAzd/N/+J/DQa9eaq4w3TQk6P7OuVpK07U9JeK1JYh3eylZ6lSdf5NvoQ0xh7xcGTZbm9A5CaUOaQNyAwXwCcyjLrzxv+zcHsNM5PAoZif11FceA2rtS+/Gy9rwxp/slEXC3lgaZW4MNUl3KqdkNpJ9FBxcjP2Ip9mTcKSjfWbnDny6TuSGDgiHCIBdyM7M/Quv1Hu+xQQPOFrY0DK2g2BxKYLDOsm+mn3YbRzvXkPZFSVUygGiE/5LGcYpLIwvO3/wyEHIx8x3NFQqmH0mNCvv2Eb0aeh0PiDoJCy475JSum1wmxUhP2ZIEnIp6U4p4+Ir7njczOinNdU0gYJvE0LAfS6L4302/o6UXLSXH4MZNfF1Aw3pNSUuSjdw6oCwSek9fowveHUwBTE84JNEK5qKnCeA09by7c/VvCRxtfhHSfilhPq1ikNqnLRS2S8NW36bOr2kKwPchA0qFeI7Ntan2gkxlaTBGmDe2elY6uTE9TEIJuZz1IuCDH/poreBLvqR0EfGWrD6nD0P/cMl2jVivnMZTzW3Bqq8DCScrKmCV5hkEgluacCqnEWQZ6U=
